use_frameworks!

target 'PTVRPlayer_Example' do
  pod 'PTVRPlayer', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "RxAppState"
  pod 'Reusable'
  pod 'Then'
  pod 'NSObject+Rx'
  pod 'SnapKit'
  pod 'QRCodeReader.swift'
  pod 'FittedSheets'
  pod 'FontAwesome.swift'
  pod 'ObjectMapper'
  pod 'MultiProgressView'
  
  target 'PTVRPlayer_Tests' do
    inherit! :search_paths
  end
end
